In [2]:
import pickle
import numpy as np
import pandas as pd

with open('ohe_dest.pkl','rb') as file:
    ohe_dest = pickle.load(file)

with open('ohe_origin.pkl','rb') as file:
    ohe_origin = pickle.load(file)

with open('ohe_unique.pkl','rb') as file:
    ohe_unique = pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler = pickle.load(file)

with open('knn.pkl','rb') as file:
    knn = pickle.load(file)

c:\Users\iamda\OneDrive\Desktop\ProjectNorm\venv\lib\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.6.1 when using version 1.6.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\iamda\OneDrive\Desktop\ProjectNorm\venv\lib\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.6.1 when using version 1.6.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\Users\iamda\OneDrive\Desktop\ProjectNorm\venv\lib\site-packages\sklearn\base.py:380: InconsistentVersionWarning: Trying to unpickle estimator KNeighborsClassifier from version 1.5.2 when using version 1.6.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [ ]:
c-8,c-22,c-2,1521,AA,CLT,DFW,936,N

In [85]:
Month = int(input('Provide the Month'))

DayofMonth = int(input('Provide the Date of Month'))

DepTime = int(input("Provide the DepTime"))

In [86]:
input_data = {
    'Month':Month,
    'DayofMoenth':DayofMonth,
    'DepTime':DepTime,
    'Origin':'SLC',	
    'Dest':'SEA',
    'Distance':689
}

In [87]:
input_data

{'Month': 10,
 'DayofMoenth': 14,
 'DepTime': 1704,
 'Origin': 'SLC',
 'Dest': 'SEA',
 'Distance': 689}

In [88]:
origin_df = ohe_origin.transform([[input_data['Origin']]]).toarray()
origin_pd = pd.DataFrame(origin_df,columns=ohe_origin.get_feature_names_out())
origin_pd

c:\Users\iamda\OneDrive\Desktop\ProjectNorm\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

,Origin_ABQ,Origin_ATL,Origin_AUS,Origin_BNA,Origin_BOS,Origin_BWI,Origin_CLE,Origin_CLT,Origin_CMH,Origin_CVG,...,Origin_SAN,Origin_SAT,Origin_SEA,Origin_SFO,Origin_SJC,Origin_SLC,Origin_SMF,Origin_SNA,Origin_STL,Origin_TPA
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [89]:
dest_df = ohe_dest.transform([[input_data['Dest']]]).toarray()
dest_pd = pd.DataFrame(dest_df,columns=ohe_dest.get_feature_names_out())
dest_pd

c:\Users\iamda\OneDrive\Desktop\ProjectNorm\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

,Dest_ABQ,Dest_ATL,Dest_AUS,Dest_BDL,Dest_BNA,Dest_BOS,Dest_BWI,Dest_CLE,Dest_CLT,Dest_CVG,...,Dest_SAN,Dest_SAT,Dest_SEA,Dest_SFO,Dest_SJC,Dest_SLC,Dest_SMF,Dest_SNA,Dest_STL,Dest_TPA
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [90]:
# df = df.drop(['Origin','Dest'],axis=1)
input_data = pd.DataFrame([input_data])
input_data

   Month  DayofMoenth  DepTime Origin Dest  Distance
0     10           14     1704    SLC  SEA       689

In [91]:

final_df = pd.concat([input_data.drop(['Origin','Dest'],axis=1),origin_pd,dest_pd],axis=1)

In [92]:
pred = scaler.transform(final_df)

c:\Users\iamda\OneDrive\Desktop\ProjectNorm\venv\lib\site-packages\sklearn\utils\validation.py:2732: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [93]:
knn.predict(pred)

array([1])